version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: qa-sys-web:python3.11
    network_mode: "service:db"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    environment:
      - PYTHON_VERSION=3.11

  db:
    image: mysql:8.0
    container_name: qa-sys-mysql8
    environment:
      MYSQL_ROOT_PASSWORD: 123456Zlx
      MYSQL_DATABASE: qasys
      MYSQL_ROOT_HOST: '%'
      TZ: Asia/Shanghai
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
      - "5000:5000"
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p123456Zlx"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
